#%RAML 1.0
---
title: API Platform Test
version: 5.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: application/xml

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/api-platform-test:
  /xml:
    post:
      displayName: Check an open XML Post request
      is: [headers.acceptHeader]

  /json:
    post:
      displayName: Check an open JSON Post request
      is: [headers.acceptHeader]

  /restricted-xml:
    post:
      displayName: Check a user-restricted XML Post request
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]

  /restricted-json:
    post:
      displayName: Check a user-restricted JSON Post request
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]

  /nrs-json:
    post:
      displayName: Check a user-restricted JSON Post request does not affect hash
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]
