#%RAML 1.0
---
title: API Platform Test
version: 5.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: application/xml

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/test/api-platform-test:
  /xml:
    post:
      displayName: Open XML Post endpoint that returns the incoming request body
      is: [headers.acceptHeader]

  /json:
    post:
      displayName: Open JSON Post endpoint that returns the incoming request body
      is: [headers.acceptHeader]

  /nrs:
    post:
      displayName: Open Post endpoint that returns SHA-256 hash of the incoming request body
      is: [headers.acceptHeader]

  /restricted-xml:
    post:
      displayName: User-restricted XML Post endpoint that returns the incoming request body
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]

  /restricted-json:
    post:
      displayName: User-restricted JSON Post endpoint that returns the incoming request body
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]

  /restricted-nrs:
    post:
      displayName: User-restricted Post endpoint that returns SHA-256 hash of the incoming request body
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]
