#%RAML 1.0
---
title: API Platform Test
version: 3.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/hello/world/api-platform-test:
  /city-details:
    /{cityName}:
      uriParameters:
        cityName:
          type: string
      /address:
        get:
          displayName: Show City & Address - Get Version
          is: [headers.acceptHeader]
        put:
          displayName: Show City & Address - Put Version
          is: [headers.acceptHeader]

      /{postcode}:
        uriParameters:
          postcode:
            type: string
        get:
          displayName: Show City & Postcode - Get Version
          is: [headers.acceptHeader]
        post:
          displayName: Show City & Postcode - Post Version
          is: [headers.acceptHeader]
        delete:
          displayName: Show City & Postcode - Delete Version
          is: [headers.acceptHeader]
