#%RAML 1.0
---
title: API Platform Test
version: 6.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/test/api-platform-test:
  /headers:
    get:
      displayName: Dummy open resource that checks if the request headers are propagated to the controller
      is: [headers.acceptHeader]

  /restricted-headers:
    get:
      displayName: Dummy user-restricted resource that checks if the request headers are propagated to the controller
      is: [headers.acceptHeader]
      (annotations.scope): "catch-the-mouse"
      securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]
