<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://xmlns.ec.eu/BusinessActivityService/ICS/ReferralManagementBAS/V1" xmlns:ccn2="http://ccn2.ec.eu/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.ec.eu/BusinessActivityService/ICS/ReferralManagementBAS/V1" name="ReferralManagementBAS">
  <wsdl:import namespace="http://xmlns.ec.eu/BusinessActivityService/ICS/ReferralManagementBAS/V1" location="CCN2.Service.Customs.Default.ICS.ReferralManagementBAS_1.0.0_1.0.0.wsdl" />
  <wsdl:binding name="ReferralManagementBASSoapBinding" type="ReferralManagementBAS">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsp:PolicyReference URI="#username_supporting_token_plaintext_password" />
    <wsdl:operation name="IE4Q04requestAdditionalInformation">
      <soap12:operation soapAction="CCN2.Service.Customs.EU.ICS.ReferralManagementBAS/IE4Q04requestAdditionalInformation" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="IE4R02provideAdditionalInformation">
      <soap12:operation soapAction="CCN2.Service.Customs.EU.ICS.ReferralManagementBAS/IE4R02provideAdditionalInformation" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="IE4Q05requestHRCM">
      <soap12:operation soapAction="CCN2.Service.Customs.EU.ICS.ReferralManagementBAS/IE4Q05requestHRCM" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="IE4R03provideHRCMResult">
      <soap12:operation soapAction="CCN2.Service.Customs.EU.ICS.ReferralManagementBAS/IE4R03provideHRCMResult" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="IsAlive">
      <soap12:operation soapAction="CCN2.Service.Customs.EU.ICS.ReferralManagementBAS/IsAlive" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CCN2.Service.Customs.EU.ICS.ReferralManagementBAS">
    <wsdl:port name="ReferralManagementBAS" binding="ReferralManagementBASSoapBinding">
      <soap12:address location="http://ccn.ws.ibt.hmrc.gov.uk:443/CCN2.Service.Customs.EU.ICS.ReferralManagementBAS" />
      <wsa:EndpointReference>
        <wsa:Address>http://ccn.ws.ibt.hmrc.gov.uk:443/CCN2.Service.Customs.EU.ICS.ReferralManagementBAS</wsa:Address>
        <wsa:Metadata>
          <ccn2:ServiceID>CCN2.Service.Customs.EU.ICS.ReferralManagementBAS</ccn2:ServiceID>
          <ccn2:ServiceName>CCN2.Service.Customs.EU.ICS.ReferralManagementBAS</ccn2:ServiceName>
          <ccn2:ServiceDescription>CCN2.Service.Customs.EU.ICS.ReferralManagementBAS</ccn2:ServiceDescription>
          <ccn2:ServiceVersion>http://ccn2.ec.eu/Version/1.0.0</ccn2:ServiceVersion>
        </wsa:Metadata>
      </wsa:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
