#%RAML 1.0
---
title: API Platform Test
version: 7.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/api-platform-test:
  :
    get:
      displayName: Dummy open resource that validate required TxM headers
      is: [headers.acceptHeader]

  /fraud-prevention:
    get:
      displayName: Dummy open resource that validate required TxM headers
      is: [headers.acceptHeader]

  /_123/{&-^}/pippo/{}/cio/{gg{oo}pp}:
    get:
      displayName: Dummy open resource that validate required TxM headers
      is: [headers.acceptHeader]