#%RAML 1.0
---
title: API Platform Test
version: 1.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/test/api-platform-test:
  /hello:
    /world:
      get:
        displayName: Get hello world
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      post:
        displayName: Post hello world
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
        body:
          application/json:
            example: |
              {
                "message": "Hello World"
              }
    /dave:
      get:
        displayName: Get hello Dave
        is: [headers.acceptHeader]
        (annotations.scope): "catch-the-mouse"
        securedBy: [ sec.oauth_2_0: { scopes: [ "catch-the-mouse" ] } ]

    /bruce:
      get:
        displayName: Get Hello Bruce
        is: [headers.acceptHeader]
        (annotations.scope): "yippie-kai-yay"
        securedBy: [ sec.x-application: { scopes: [ "yippie-kai-yay" ] } ]

    /friend:
      get:
        displayName: Get hello friend
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
        queryParameters:
          givenName:
            description: Given name
            type: string
            required: true
          lastName:
            description: Family name
            type: string
            required: false
      post:
        displayName: Post hello friend
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
        body:
          application/json:
            example: |
              {
                "message": "Hello World"
              }
    /buddies:
      get:
        displayName: Get hello buddies
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
        queryParameters:
          name:
            description: Given name
            type: string
            required: false
      post:
        displayName: Post hello buddies
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
        body:
          application/json:
            example: |
              {
                "message": "Hello World"
              }
    /family:
        /{givenName}:
          uriParameters:
            givenName:
              description: Given name
              type: string
          get:
            displayName: Get family member
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          put:
            displayName: Post family member
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
            body:
              application/json:
                example: |
                  {
                    "message": "Hello World"
                  }
          /pets:
            get:
              displayName: Get pets
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            post:
              displayName: Post pets
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
              body:
                application/json:
                  example: |
                    {
                      "message": "Hello World"
                    }
            /{petName}:
              uriParameters:
                petName:
                  description: Pet name
                  type: string
              get:
                displayName: Get pet
                is: [headers.acceptHeader]
                securedBy: [ sec.x-application ]
              put:
                displayName: Put pet
                is: [headers.acceptHeader]
                securedBy: [ sec.x-application ]
                body:
                  application/json:
                    example: |
                      {
                        "message": "Hello World"
                      }
              /weight:
                get:
                  displayName: Get pet weight
                  is: [headers.acceptHeader]
                  securedBy: [ sec.x-application ]
                  body:
                    application/json:
                      example: |
                        {
                          "message": "Hello World"
                        }
                post:
                  displayName: Post pet weight
                  is: [headers.acceptHeader]
                  securedBy: [ sec.x-application ]
                  body:
                    application/json:
                      example: |
                        {
                          "message": "Hello World"
                        }
          /preference:
            get:
              displayName: Get preference
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
              queryParameters:
                preferenceType:
                  description: Preference type
                  type: string
                  required: false
            post:
              displayName: Post preference
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
              body:
                application/json:
                  example: |
                    {
                      "message": "Hello World"
                    }

  /ni/{nino}:
    uriParameters:
      nino:
        description: National Insurance Number. This should be provided without spaces (e.g. AA999999A), as spaces in NINOs will be forbidden in a future version of the API.
        type: string
    /self-employments:
      post:
        displayName: Add a self-employment business [test only]
        description: Add a self-employment business. This API is not available in production.
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      get:
        displayName: List all self-employment businesses
        description: List all self-employment businesses
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      /{selfEmploymentId}:
        description: Self-employment business
        uriParameters:
          selfEmploymentId:
            displayName: Self-employment ID
            description: An identifier for the self-employment business, unique to the customer
            type: string
        put:
          displayName: Update a self-employment business [test only]
          description: Update a self-employment business. This API is not available in production.
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
        get:
          displayName: Get a self-employment business
          description: Get a self-employment business
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
        /obligations:
          get:
            displayName: Retrieve self-employment business obligations
            description: Retrieve self-employment business obligations
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
        /periods:
          post:
            displayName: Create a self-employment update period
            description: Create a self-employment update period for submission of periodic data i.e incomes and expenses.
                         Submissions which do not include any incomes or expenses are invalid.
                         You should submit zero values if you do not have incomes or expenses.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          get:
            displayName: List all self-employment update periods [test only]
            description: List all self-employment update periods. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          /{periodId}:
            uriParameters:
              periodId:
                description: Update period ID
                type: string
            get:
              displayName: Get a self-employment update period [test only]
              description: Get a single self-employment update period for a given identifier. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            put:
              displayName: Update a self-employment update period [test only]
              description: Update a self-employment update period. This API is not available in production.
                           Submissions  which do not include any incomes or expenses are invalid.
                           You should submit zero values if you do not have incomes or expenses.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            post:
              displayName: Update a self-employment update period [test only]
              description: Update a self-employment update period. This API is not available in production.
                           Submissions  which do not include any incomes or expenses are invalid.
                           You should submit zero values if you do not have incomes or expenses.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
        /taxYear:
          uriParameters:
            taxYear:
              description: The tax year the data applies to
              type: string
              example: 2017-18
          put:
            displayName: Update a self-employment annual summary [test only]
            description: Update a self-employment annual summary for a tax year. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          get:
            displayName: Get a self-employment annual summary [test only]
            description: Get a self-employment annual summary for a tax year. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
    /uk-properties:
      post:
        displayName: Add a UK property business [test only]
        description: Add a UK property business. This API is not available in production.
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      get:
        displayName: Get a UK property business
        description: Get a UK property business
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      /obligations:
        get:
          displayName: Retrieve all UK property business obligations
          description: Retrieve all UK property business obligations
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
      /other:
        /periods:
          post:
            displayName: Create a non FHL UK property update period
            description: Create a non FHL UK property update period for submission of periodic data i.e incomes and expenses.
                         Submissions  which do not include any incomes or expenses are invalid.
                         You should submit zero values if you do not have incomes or expenses.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          get:
            displayName: List all non FHL UK property update periods [test only]
            description: List all non FHL UK property update periods. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          /{periodId}:
            uriParameters:
              periodId:
                displayName: Update period ID
                description: An identifier for the period
                type: string
            get:
              displayName: Get a non FHL UK property update period [test only]
              description: Get a non FHL UK property update period for a given identifier. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            put:
              displayName: Update a non FHL UK property update period [test only]
              description: Update a non FHL UK property update period. This API is not available in production.
                           Submissions  which do not include any incomes or expenses are invalid.
                           You should submit zero values if you do not have incomes or expenses.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
        /{taxYear}:
            displayName: Annual Summary
            uriParameters:
              taxYear:
                description: The tax year the data applies to
                type: string
                example: 2017-18
            put:
              displayName: Update a non-FHL UK property business annual summary [test only]
              description: Update a non-FHL UK property business annual summary for a tax year. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            get:
              displayName: Get non FHL UK property business annual summary [test only]
              description: Get non FHL UK property business for a tax year. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
      /furnished-holiday-lettings:
        /periods:
          post:
            displayName: Create a FHL UK property update period
            description: Create a FHL UK property update period for submission of periodic data i.e incomes and expenses.
                         Submissions which do not include any incomes or expenses are invalid.
                         You should submit zero values if you do not have incomes or expenses.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          get:
            displayName: List all FHL UK property update periods [test only]
            description: List all FHL UK property update periods. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          /{periodId}:
            uriParameters:
              periodId:
                displayName: Update period ID
                description: An identifier for the period
                type: string
            get:
              displayName: Get a FHL UK property update period [test only]
              description: Get a FHL UK property update period for a given identifier. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            put:
              displayName: Update a FHL UK property update period [test only]
              description: Update a FHL UK property update period. This API is not available in production.
                           Submissions which do not include any incomes or expenses are invalid.
                           You should submit zero values if you do not have incomes or expenses.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
        /{taxYear}:
            displayName: Annual Summary
            uriParameters:
              taxYear:
                description: The tax year the data applies to
                type: string
                example: 2017-18
            put:
              displayName: Update a FHL UK property business annual summary [test only]
              description: Update a FHL UK property business annual summary for a tax year. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
            get:
              displayName: Get a FHL UK property business annual summary [test only]
              description: Get a FHL UK property business annual summary for a tax year. This API is not available in production.
              is: [headers.acceptHeader]
              securedBy: [ sec.x-application ]
    /dividends:
      /{taxYear}:
        displayName: Annual Summary
        uriParameters:
          taxYear:
            description: The tax year the data applies to
            type: string
            example: 2017-18
        put:
          displayName: Update a dividends income annual summary [test only]
          description: Update a dividends income annual summary for a tax year. This API is not available in production.
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
        get:
          displayName: Get dividends income annual summary [test only]
          description: Get dividends income for a tax year. This API is not available in production.
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
    /savings-accounts:
      post:
        displayName: Add a savings account [test only]
        description: Add a savings account. This API is not available in production.
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      get:
        displayName: List all savings accounts [test only]
        description: List all savings accounts. This API is not available in production.
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      /{savingsAccountId}:
        put:
          displayName: Update a savings account [test only]
          description: Update a savings account. This API is not available in production.
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
        get:
          displayName: Get a savings account [test only]
          description: Get a savings account. This API is not available in production.
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
        /{taxYear}:
          put:
            displayName: Update a savings account annual summary [test only]
            description: Update a savings account annual summary for a given tax year. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
          get:
            displayName: Get a savings account annual summary [test only]
            description: Get a savings account annual summary for a given tax year. This API is not available in production.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
    /calculations:
      post:
        displayName: Trigger a tax calculation [canned]
        description: Trigger a tax calculation. Please note that this API will return pre-defined responses that are representative of what may be returned in a future version of this API.
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
      /{taxCalculationId}:
        uriParameters:
          taxCalculationId:
            description: The ID of the tax calculation
            type: string
        get:
          displayName: Retrieve a tax calculation [canned]
          description: Retrieve a tax calculation. Please note that this API will return pre-defined responses that are representative of what may be returned in a future version of this API.
          is: [headers.acceptHeader]
          securedBy: [ sec.x-application ]
  /error:
    /{errorCode}:
      uriParameters:
        errorCode:
          description: Error code
          type: integer
      get:
        displayName: Get error
        is: [headers.acceptHeader]
  /notifications:
    post:
      displayName: Trigger notification
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
  /destination:
    /notifications:
      post:
        displayName: Handle notification push
        is: [headers.acceptHeader]
        securedBy: [ sec.x-application ]
        queryParameters:
          status:
            description: Status that the endpoint will return
            type: integer
            required: false
          delayInSeconds:
            description: Delay in seconds before the endpoint returns the response
            type: integer
            required: false
